# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogdjango', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='\u7167\u7247\u4e0a\u4f20\u65f6\u95f4')),
                ('photo', models.ImageField(upload_to=b'userphoto')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogdjango.Blog')),
            ],
            options={
                'ordering': ['-upload_time'],
                'db_table': 'blog_photo',
                'verbose_name': '\u7167\u7247',
            },
        ),
        migrations.AddField(
            model_name='userdetail',
            name='head_photo',
            field=models.ImageField(null=True, upload_to=b'face'),
        ),
    ]
